networks:
  traefik:
    external: false
    name: traefik

volumes:
  staticfiles:
    external: false
    name: staticfiles

services:
  traefik:
    image: traefik:3
    container_name: traefik
    restart: always
    command:
      - --configFile=/etc/traefik/traefik.yml

    ports:
      - "80:80"
      - "443:443"
    networks:
      - traefik
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./dynamic_conf:/etc/traefik/dynamic_conf:ro
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro

  static:
    image: nginx:alpine
    volumes:
      - staticfiles:/usr/share/nginx/html:ro
    networks:
      - traefik
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tagmate-static.rule=Host(`static.${DOMAIN}`)"
      - "traefik.http.routers.tagmate-static.entrypoints=websecure"
      - "traefik.http.routers.tagmate-static.tls.certresolver=le"
      - "traefik.http.services.tagmate-static.loadbalancer.server.port=80"
      - "traefik.http.routers.tagmate-secure.middlewares=restricted-ips@file"
