networks:
  traefik:
    external: false
    name: traefik

volumes:
  staticfiles:
    external: false
    name: staticfiles

services:
  traefik:
    image: traefik:3
    container_name: traefik
    restart: always
    command:
      - --configFile=/etc/traefik/traefik.yml

    ports:
      - "80:80"
      - "443:443"
    networks:
      - traefik
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./dynamic_conf:/etc/traefik/dynamic_conf:ro
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro

  static-init:
    image: python:3.13-alpine
    command: >
      sh -c "mkdir -p /app/staticfiles &&
             chown -R 1000:1000 /app/staticfiles"
    volumes:
      - staticfiles:/app/staticfiles
    restart: "no"

  static:
    image: nginx:alpine
    container_name: static
    volumes:
      - staticfiles:/usr/share/nginx/html:ro
      - ./nginx-static.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - traefik
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.static.loadbalancer.server.port=80"
      - "traefik.http.routers.static-secure.rule=Host(`static.${DOMAIN}`)"
      - "traefik.http.routers.static-secure.entrypoints=websecure"
      - "traefik.http.routers.static-secure.tls.certresolver=le"
