services:
  traefik:
    image: traefik:3
    environment:
      - TRAEFIK_ACME_EMAIL
      - DASHBOARD_USER
      - RESTRICTED_IPS
      - DOMAIN

    container_name: traefik
    restart: always
    command:
      - --configFile=/etc/traefik/traefik.yml
      - --providers.docker.pollingInterval=15s
    ports:
      - "80:80"
      - "443:443"
    networks:
      - traefik
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./dynamic_conf:/etc/traefik/dynamic_conf:ro
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  traefik:
    external: true